// 家康AI小説「狸の笑い」— 全話プロット定義
// 第一部「三成、四百年後の独白」ep01〜14

export const plots = [
  {
    episode: 1,
    title: '従順',
    narrator: '三成',
    historicalFact: '秀吉死去・五大老五奉行体制発足',
    misreading: '家康は制度に従うと思った',
    blankTheme: 'なぜ家康は従順に見えたのか',
    aiHighlight: '弔問の場の顔ぶれの不自然さ',
    tanakaPhase: '無視',
  },
  {
    episode: 2,
    title: '縁組',
    narrator: '三成',
    historicalFact: '慶長3年秋〜冬、家康が五大老合意なしに諸大名との縁組を進める（伊達政宗・加藤清正・福島正則ら武断派との婚姻同盟）',
    misreading: 'これは手続き違反であり、警告すれば止まると思った',
    blankTheme: '家康は縁組を通じて何を約束したのか',
    aiHighlight: '縁組の相手が武断派中心という偏り——制度違反ではなく網の構築だった',
    tanakaPhase: '無視',
  },
  {
    episode: 3,
    title: '利家',
    narrator: '三成',
    historicalFact: '慶長3年末〜4年正月、前田利家の病状悪化・伏見の政治的緊張の高まり',
    misreading: '利家が生きている間は抑止力が機能すると思った',
    blankTheme: '利家は三成に何を伝えたかったのか',
    aiHighlight: '利家の病床への来訪者記録——家康が利家を「立てた」頻度の異常な高さ',
    tanakaPhase: '無視',
  },
  {
    episode: 4,
    title: '正月',
    narrator: '三成',
    historicalFact: '慶長4年正月6日、武断派七将（加藤清正・福島正則・黒田長政・細川忠興・浅野幸長・加藤嘉明・藤堂高虎）が三成邸を包囲しようとした事件',
    misreading: '武断派の怒りは感情的なものであり、論理で解決できると思った',
    blankTheme: '三成は包囲される前の数時間、屋敷で何を考えていたか',
    aiHighlight: '七将の行動に事前の統率がある——誰かが指揮していた痕跡',
    tanakaPhase: '無視',
  },
  {
    episode: 5,
    title: '仲裁',
    narrator: '三成',
    historicalFact: '慶長4年正月、家康が武断派七将と三成の間を仲裁。三成は奉行職を辞して佐和山へ退く',
    misreading: '家康の仲裁は制度への誠実さから来ると思った',
    blankTheme: '仲裁の席で家康と三成は何を話したか',
    aiHighlight: '仲裁の結果が三成の除去という、家康にとって都合のいい帰結に終わった一致',
    tanakaPhase: '無視',
  },
  {
    episode: 6,
    title: '閏三月',
    narrator: '三成',
    historicalFact: '慶長4年閏3月3日、前田利家死去。直後から徳川優位の政治状況が鮮明化',
    misreading: '利家が死んでも制度は機能する、人が変わっても仕組みは残ると思った',
    blankTheme: '利家の臨終の間で何が語られたか——誰が最後に見舞ったか',
    aiHighlight: '利家死去当日の伏見における家康の行動記録の空白',
    tanakaPhase: '困惑',
  },
  {
    episode: 7,
    title: '佐和山',
    narrator: '三成',
    historicalFact: '慶長4年〜5年、三成の佐和山退去期間。表舞台から消えた約一年間',
    misreading: '退去は一時的な退避であり、状況が整えば復帰できると思った',
    blankTheme: '佐和山で三成は毎日何をしていたのか——記録の外の時間',
    aiHighlight: '退去中に三成が送った書状の宛名の変化——孤立の進行',
    tanakaPhase: '困惑',
  },
  {
    episode: 8,
    title: '直江状',
    narrator: '三成',
    historicalFact: '慶長5年4月、上杉景勝家老・直江兼続が家康の詰問に対して挑発的な書状（直江状）を送付。家康の上杉征伐の口実となる',
    misreading: '上杉の抵抗が家康を牽制し、均衡をもたらすと思った',
    blankTheme: '直江兼続はなぜあれほど挑発的な文言を選んだのか',
    aiHighlight: '直江状の文体が上杉の軍事力に見合わないほど強硬——計算か、それとも罠か',
    tanakaPhase: '困惑',
  },
  {
    episode: 9,
    title: '決断',
    narrator: '三成',
    historicalFact: '慶長5年7月、三成が佐和山を出て行動を開始。大垣経由で大坂へ向かい西軍挙兵へ',
    misreading: '今動かなければ永遠に動けない、という計算が正しいと思った',
    blankTheme: '何が三成を動かした最後の引き金だったのか',
    aiHighlight: '決起直前に三成が送った書状の宛名と、実際に応じた者の乖離',
    tanakaPhase: '困惑',
  },
  {
    episode: 10,
    title: '毛利',
    narrator: '三成',
    historicalFact: '慶長5年7月、毛利輝元が西軍総大将として大坂城に入る。豊臣政権の名義上の守護者として担ぎ上げられる',
    misreading: '毛利の参加は本気の軍事力の提供を意味すると思った',
    blankTheme: '輝元は総大将就任を打診された瞬間、何を計算したか',
    aiHighlight: '輝元の大坂入城後の行動の消極性——総大将でありながら前線に出ない',
    tanakaPhase: '困惑',
  },
  {
    episode: 11,
    title: '前夜',
    narrator: '三成',
    historicalFact: '慶長5年9月14日夜、関ヶ原前夜の布陣。小早川秀秋が松尾山に陣取る',
    misreading: '数的優位と地の利があれば戦略は機能すると思った',
    blankTheme: '三成は前夜に何を計算し、何を見落としたか',
    aiHighlight: '小早川秀秋の松尾山への布陣位置——西軍・東軍どちらからも奇妙に見えた配置',
    tanakaPhase: '困惑',
  },
  {
    episode: 12,
    title: '九月十五日',
    narrator: '三成',
    historicalFact: '慶長5年9月15日、関ヶ原の戦い。午前中の膠着から小早川の裏切りによる西軍崩壊。六時間で決着',
    misreading: '小早川が動くまでは均衡が保てる、その間に局面を変えられると思った',
    blankTheme: '三成は戦場の崩壊をどの瞬間に、どの順番で認識したか',
    aiHighlight: '小早川が動かなかった午前中の長さ——家康はいつ確信を持ったか',
    tanakaPhase: '困惑',
  },
  {
    episode: 13,
    title: '田中吉政',
    narrator: '三成',
    historicalFact: '慶長5年9月下旬、敗走した三成が伊吹山中に潜伏。旧知の田中吉政の軍勢に発見・捕縛される',
    misreading: '逃げ延びれば再起の機会があると思った',
    blankTheme: '捕縛の瞬間、三成と田中吉政は何を話したか',
    aiHighlight: '捕縛した田中吉政は三成の元同僚・旧知の間柄——なぜ田中が捜索にあたったのか',
    tanakaPhase: '困惑',
  },
  {
    episode: 14,
    title: '六条河原',
    narrator: '三成',
    historicalFact: '慶長5年10月1日、石田三成・小西行長・安国寺恵瓊の処刑。家康は処刑の場に姿を現さなかった',
    misreading: '死の直前まで「なぜ負けたか」を計算しようとした——答えが出れば、終われると思った',
    blankTheme: '三成は処刑台の上で最後に何を見たか',
    aiHighlight: '家康が処刑の場に来なかったという記録——なぜ来なかったのか',
    tanakaPhase: '接触',
  },
];
